version: '3'
networks:
  eval:
    external: true

services:
  cadvisor: 
    privileged: true
    image: gcr.io/cadvisor/cadvisor:latest 
    ports: 
      - "8080:8080"
    command: 
      ["-storage_driver=influxdb",
      "-storage_driver_db=engines",
      "-housekeeping_interval=100ms",
      "-storage_driver_buffer_duration=3s",
      "-storage_driver_host=influxsrv:8086"]
      
    volumes: 
      - /:/rootfs:ro
      - /var/run:/var/run:rw 
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks: 
      - eval 


